[build.environment]
  NODE_VERSION="16"
[build]
  publish="dist"
  command="npm run generate"
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
  output_path = "reports/lighthouse.html"
